### ISSUE TITLE
Audio still not working

### ISSUE THREAD

**Issue by NikG123** [Sailfish-On-Vince/issues#2]
Audio still doesn't work in alpha9

**Comment by 0312birdzhang** [comment]
try reboot and see if it works.

Thank you for your feedback.

**Comment by 0312birdzhang** [comment]
If it still not work, try use `zypper ref && zypper up` to update to latest build

**Comment by 0312birdzhang** [comment]
[sailfishos-vince-release-2.1.4.14-beta1.zip](http://images.devaamo.fi/sfe/vince/sailfishos-vince-release-2.1.4.14-beta1.zip) released with data fixed, please use this one.
