### ISSUE TITLE
Bad exit status from /var/tmp/rpm-tmp.wro33X (%build)

### ISSUE THREAD

**Issue by taskforpid** [Sailfish-On-Vince/issues#24]
Hello!

I am trying to build image 3.0.1.11 and I've got this mistake when I am trying to build dhd
```
rpm/dhd/helpers/build_packages.sh -d
```
```
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.wro33X (%build)
No journal files were found.
Failed to seek to cursor: Invalid argument
```

And stable anbox on last sfos 3.0.1.11 or upper?   

Regards

**Comment by 0312birdzhang** [comment]
Why are you building 3.0.1.11 yourself? You can download it at gitlab.

If build failed, it will tell you where is the full log path.

Anbox is working on 3.0.1.11, but it's very buggy.

**Comment by taskforpid** [comment]
thanks for reply

cuz I had bug in input method my screen is black when shows keyboard 
How i can fix that?

Better way to run anbox minimal bugs?

**Comment by taskforpid** [comment]
can you check my success env for enchilada? and I trying to use that for vince with changed version sfos and los hybris 
in my env repo

**Comment by 0312birdzhang** [comment]
Black screen in sailfishos or anbox?

**Comment by taskforpid** [comment]
black screen when i trying to input in anbox on any apps

**Comment by taskforpid** [comment]
Will anbox work on your last ci building 3.3.0.16 guide?
I need to try run that by myself

**Comment by 0312birdzhang** [comment]
> Will anbox work on your last ci building 3.3.0.16 guide?
> I need to try run that by myself

No, it's not working.

**Comment by taskforpid** [comment]
Ok, thank you for reply!

So, what i need to resolve bug with black screen

Regards

**Comment by 0312birdzhang** [comment]
> So, what i need to resolve bug with black screen

Do you have this https://github.com/Sailfish-On-Vince/anbox/commit/8b4c046b7bbf6b3b0db849dd78110b24bb0b6d49 ?
It's not working and will introduce black screen bug.

**Comment by taskforpid** [comment]
I was using anbox from here I do not know
ssu ar birdzhang-anbox http://repo.merproject.org/obs/home:/birdzhang:/anbox/sailfishos_3.0.1.11_armv7hl/

```
make
make install
```
shows errors
other way?

**Comment by 0312birdzhang** [comment]
As [waydroid ](https://github.com/waydroid) will be [supported ](https://twitter.com/adampigg/status/1442379954386255873) on sfos, so close this issue.
