### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by NikG123** [Sailfish-On-Vince/issues#3]
Web browsers opens to a white screen. By tapping and reopening the app i managed to get it to a black screen where i could type, but I wasn't able to see it (because what i typed was also black - on a black background). The keyboard popped  up on the block screen and i was able to type. But when i entered for ex. google.com and pressed enter (return) it opened the white page/screen again.

**Comment by 0312birdzhang** [comment]
Yes, this is a bug. Try use webprivate or webcat insted.

**Comment by 0312birdzhang** [comment]
Fixed at beta1  https://github.com/Sailfish-On-Vince/droid-hal-vince/commit/d2cf939b0db60c1dd85d8f332c6c21018015d080
