### ISSUE TITLE
No SIM card inserted

### ISSUE THREAD

**Issue by EvgenyNerush** [Sailfish-On-Vince/issues#6]
Thanks a lot for your adaptation! I have accidentally turned off my SIM card (in the Settings app, Connectivity/SIM cards), and now I cann't turn it on. The field is "No SIM card inserted". I have tried to remove and insert the SIM card, reboot, but this doesn't help. If I boot to lineage-14.1-20180304, SIM works fine. However, sailfish 2.1.4.14-beta4 doesn't see SIM.

**Comment by 0312birdzhang** [comment]
Thanks for your feedback. 
Sorry for that, i will fingure it out.

**Comment by 0312birdzhang** [comment]
@EvgenyNerush Hi, i found a solution by use csd test.
type `*#*#310#*#*` in Phone app or type `csd` in Terminal, then accept the disclaimer, and then click `Individual tests`, and at the bottom of listview click `SIM card`, just wait it become to `Success`, the SIM card will back.

**Comment by EvgenyNerush** [comment]
Unfortunately, I do not see `SIM card` in the list of Individual tests (`USB OTG` is the last), and in the list of all the tests I don't see it also. The solution for me now is just to reinstall Sailfish and don't press the SIM button in Settings ).

**Comment by 0312birdzhang** [comment]
Maybe this file(`/usr/share/csd/settings.d/hw-settings.ini`) would be helpful https://github.com/Sailfish-On-Vince/droid-config-vince/blob/5ea331b75c9613a83460074baf49a667cf972221/sparse/usr/share/csd/settings.d/hw-settings.ini

I will ask other porters at `#sailfishos-porters` for more help to fix it.

**Comment by EvgenyNerush** [comment]
I don't want to reproduce this bug again. Now, with Sailfish OS reinstalled, SIM is turned on and in `csd` I see `SIM card: Pass`.

**Comment by EvgenyNerush** [comment]
Everything else is ok, so thank for your port again.

**Comment by 0312birdzhang** [comment]
There is a bug at 2.1.4.14-beta4, when after use camera record, the camera app will become no response.
You need to reboot to fix it.
But 2.1.4.14-beta4 is the most stable version until now, 2.2.0.29 have more bugs 😂

**Comment by zeonin** [comment]
Hi! I hit the same issue with disabling the SIM card.

I was able to solve it by navigating to Settings -> Data counters and tapping `Enable` under the Cellular Data section.

**Comment by 0312birdzhang** [comment]
@zeonin Good ! BTW, what's your SailfishOS version ?

**Comment by zeonin** [comment]
@0312birdzhang I'm currently on 2.1.4.14 until the bugs in 2.2.0.29 are worked out.

**Comment by 0312birdzhang** [comment]
This bug is totaly solved now, with https://github.com/Sailfish-On-Vince/device_xiaomi_vince/commit/c91daf00526d741c6a2992ce3e63757482e8dc2b
